logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

server:
  port: 5150
  binding: localhost
  host: http://localhost
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/static"
        path: "assets/static"
      fallback: "assets/static/404.html"
