logger:
  enable: true
  pretty_backtrace: false
  level: info
  format: json

server:
  port: 5150
  binding: 0.0.0.0
  host: https://cidadao-de-olho.local
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/static"
        path: "assets/static"
      fallback: "assets/static/404.html"
