logger:
  enable: false
  pretty_backtrace: false
  level: warn
  format: compact

server:
  port: 5151
  binding: localhost
  host: http://localhost
  middlewares:
    static:
      enable: true
      must_exist: true
      precompressed: false
      folder:
        uri: "/static"
        path: "assets/static"
      fallback: "assets/static/404.html"
